insight_text = {
    "scaled_daily_active_users_dau": "**Increasing DAU** appears to be associated with **lower revenue per user** "
                                     "suggesting diminishing monetization efficiency at higher user volumes. "
                                  "Developers should focus on backend stability to support scalable monetization strategies "
                                     "such as load-balanced offers, personalized experiences and performance optimization to "
                                     "maintain value at scale. "
                                     "The pattern also hints at:\n"
                                     "- Saturation of monetizable users.\n"
                                     "- Spike in free users not engaging in purchases.\n"
                                     "- Backend or UX limitations at higher user loads.\n",
    "scaled_new_registrations": "Although **new registrations increase, revenue per user decreases**, "
                                "indicating diminishing marginal returns from new user acquisition. "
                                "This pattern suggests that acquiring new players isn't enough. "
                                "Marketers should focus on activation, retention and "
                                "conversion strategies for these users to sustain revenue growth. "
                                "**Strategic Takeaways for Marketers:\n"
                                "- Shift focus from acquisition to early-game monetization.\n"
                                "- Introduce welcome offers, onboarding journeys or "
                                "loyalty nudges to drive early purchases.\n"
                                "- Use segmentation to distinguish high-value new users from passive ones.",
    "stream_viewers_per_player": "As stream viewers per player increases, so does revenue per user, indicating that "
                                 "stream popularity is positively correlated with monetization. "
                                 "This suggests that players whose gameplay is streamed more often, "
                                 "either by themselves or others, tend to generate higher revenue.\n"
                                 "Strategic Takeaways for Marketers:\n"
                                 "- Invest in streamer partnerships and community-driven streaming.\n"
                                 "- Highlight and promote gameplay from popular or competitive players,\n"
                                 "- Create stream-friendly features or incentives (e.g, rewards for players "
                                 "whose sessions are streamed, streamer badges).\n"
                                 "- Leverage this insight to launch influencer-based "
                                 "campaigns targeting active viewers.",
    "purchases_per_session": "Note on x-axis scaling:\n\n"
                             "- The x-axis in the PDP plot reflects a wide range of purchase value per session "
                             "and the tick marks appear unevenly spaced.\n"
                             "- This is due to the highly right-skewed distribution of the feature, where the "
                             "majority of players make very few purchases, but a small number of users "
                             "contribute to extreme high values.\n"
                             "- Rather than adjusting or transforming the ais, this skew has been retained ro reflect "
                             "the real-world behavior, highlighting that monetization is heavily influenced by a small, "
                             "high-spending user base.\n\n"
                             "**More In-Game Purchases per Session Drives Higher Revenue**\n\n"
                             "The PDP plot reveals a strong upward trend in revenue per user as the number of "
                             "purchases per session increases, up to ~2000 purchases/session where the "
                             "curve starts to plateau.\n\n"
                             "This indicates:\n"
                             "- Active in-game purchasing behavior is highly monetizable.\n"
                             "- There's a clear marginal gain in revenue with increases purchase activity per session "
                             "especially between 500 and 1500 purchases.\n"
                             "- Beyond ~2000 purchases, revenue flattens slightly, indicating a sturation point or "
                             "diminishing return on session purchases.\n\n"
                             "Strategic Takeaways for PMs:\n"
                             "- Design systems that promote in-session purchases, such as dynamic rewards, time-limited offers "
                             "and mid-session unlocks.\n"
                             "- Identify conversion triggers that can increase purchase frequency within a session.\n"
                             "- Use this insight to segment power buyers vs. casual buyers, and tailor "
                             "experiences accordingly.\n"
                             "- Monitor the sweet spot(~500 - 1500 purchases) to optimize monetization "
                             "without overwhelming users.",
    "scaled_social_media_mentions": "**Social Buzz and Revenue have a Nonlinear Relationship.**\n"
                                    "Revenue per user initially increases with more social media mentions, "
                                    "but shows a dip between ~0.4 to 0.7 of scaled mentions, before rising "
                                    "again at higher levels (>0.75).\n"
                                    "This indicates:\n"
                                    "- Moderate levels of social media buzz may not always translate "
                                    "into higher revenue, possibly due to neutral or negative buzz, fatigue or "
                                    "non-monetized virality.\n"
                                    "- At very high levels of buzz, revenue begins to climb again, possibly "
                                    "due to viral spikes, conversion-driven campaigns, or event-based engagements.\n\n"
                                    "Strategic Takeaways for Marketers:\n"
                                    "- Track sentiment and engagement type, not just the volume of mentions.\n"
                                    "- Avoid over-reliance on mid-scale campaigns "
                                    "that create noise but don't drive revenue.\n"
                                    "- Invest in high-impact campaigns that breaks into higher buzz tiers "
                                    "(e.g, influencer collabs, viral challenges).\n"
                                    "- Consider combining buzz metrics with click-through, retention "
                                    "purchase intent data.",
    "scaled_stream_viewership": "The PDP indicates a steady decline in revenue per user as overall stream "
                                "viewership increases (e.g, YouTube, Twitch).\n"
                                "- Exposure through third-party platforms doesn't automatically "
                                "translate to monetization.\n"
                                "- High external buzz can be misleading without proper funneling "
                                "mechanism back into the game.\n"
                                "- Many viewers may not be active players or may engage only passively without "
                                "converting to in-game actions or purchases.\n"
                                "In contrast to:\n"
                                "- Stream Viewers per Player (previous insight) where higher player-centric streaming "
                                "popularity was positively associated with revenue, indicating that creator-driven "
                                "or player-focused streaming adds more value.\n\n"
                                "Strategic Takeaways for Marketers:\n"
                                "- Reassess KPIs. Prioritize engaged traffic over vanity metrics like "
                                "total view count.\n"
                                "- Integrate stream-to-play conversion strategies such as including referral links, "
                                "in-game rewards for watchers or influencer codes.\n"
                                "- Consider in-game event streaming or first-party platforms where user journeys "
                                "can be tracked and influenced more directly.",
    "influencer_endorsements": "**Influencer Endorsements Positively Correlate with Revenue.**\n\n"
                               "The PDP reveals a strong linear increase in revenue per user as influencer "
                               "endorsements increase, even with binary (0/1) input.\n\n"
                               "This suggests: \n"
                               "- Titles backed by influencers (via streams, social media or shoutouts) "
                               "consistently outperform others in monetization.\n"
                               "- Influencers appear to drive quality traffic that converts, "
                               "not just passive attention.\n"
                               "- Even a single endorsement creates a measurable uptick in expected revenue, "
                               "which could scale further with multiple campaigns.\n\n"
                               "Strategic Takeaways for Marketers:\n"
                               "- Prioritize influencer partnerships as a core part of launch and growth strategies.\n"
                               "- Focus not just on follower count, but ensure alignment between influencer audience "
                               "and game genre or platform.\n"
                               "- Experiment with micro-influencers too. Multiple endorsements could create compound "
                               "impact.\n"
                               "Consider measuring campaign performance through PDP shifts in future models.",
    "release_month_freq": "There is a downward trend in revenue as release frequency across months increases. "
                           "This may indicate over-saturating releases across months dilutes impact, and "
                           "games launched during less frequent release windows tend to perform better in terms of "
                           "monetization.\n\n"
                           "Note about Skewed Distribution:\n"
                           "- The skew in tick marks suggests that only a few months have "
                           "high release concentrations.\n"
                           "- This reinforces the idea that crowded launch periods may not yield better revenue.\n"
                           "PMs should evaluate seasonal competition and potentially stagger releases to avoid "
                           "launch fatigue.",
    "release_dayofweek_freq": "This PDP shows how frequently games are released on specific days of the week"
                              "(Monday, Tuesday, etc.,) and how that correlates with revenue.\n\n"
                              "- There is a rise and dip pattern, suggesting that some days might yield better "
                              "monetization than others.\n"
                              "- However, the differences are subtle and the range of partial dependence "
                              "is narrow (~0.575 - 0.5755), indicating marginal influence overall.\n"
                              "- There may also be some data imbalance, where only certain days dominate the dataset, "
                              "limiting interpretability.",
    "release_quarter_freq": "Revenue per user declines as the release frequency increases within a quarter, "
                            "indicating potential over-saturation.\n\n"
                            "Strategic Takeaways for PMs:\n"
                            "- PMs should avoid clustering too many launches in the same quarter.\n"
                            "- Spacing out major releases can help maximize revenue per title and reduce "
                            "competition for user attention.",
    "dau_bin_Very High": "The PDP shows a steady decline in revenue per user for the Very High DAU tier.\n\n"
                         "Strategic Takeaways for PMS:\n"
                         "- A very large daily active user base may indicate saturation "
                         "without sufficient monetization.\n"
                         "- PMs should explore whether high DAU is driven by non-paying users and introduce "
                         "tiered offerings, personalized pricing or loyalty programs to convert scale into "
                         "revenue.",
    "dau_bin_Medium": "The PDP shows a consistent positive correlation between the Medium DAU tier "
                      "and revenue per user.\n\n"
                      "Strategic Takeaways for PMs:\n"
                      "- This user segment may represent an ideal engagement-to-monetization balance.\n"
                      "- PMs should nurture this segment by focusing on mid-tier features, scalable offers "
                      "and retention campaigns to continue driving sustainable revenue.",
    "dau_bin_Low": "This PDP reveals a linear increase in revenue per user as the proportion of users in "
                   "the Low DAU tier rises.\n\n"
                   "Strategic Takeaway for PMs:\n"
                   "- Even low engagement user segments show strong monetization potential.\n"
                   "- PMs can explore micro-transaction models, targeted promotions or occasional "
                   "premium offerings to capture value from this group without requiring sustained engagement.",
    "dau_bin_High": "The trend line shows a steady decline in revenue per user as the share of "
                    "users in the High DAU tier increases.\n\n"
                    "Strategic Takeaway for PMs:\n"
                    "- This could indicate diminishing returns from high-frequency users, possibly "
                    "due to monetization fatigue or reliance on non-paying players.\n"
                    "- PMs may consider refining reward systems, introducing tiered monetization mechanics, or "
                    "focusing on retention tactics that balance playtime with spend behavior."

}